### ISSUE TITLE
Read settings.json file

### ISSUE THREAD

**Issue by Janmm14** [helios-decompiler/Helios#19]
I see in ```C:Users\<User>\.helios\settings.json``` are decompiler settings saved.
The file seems to be safed when helios shuts down, the content is updated.

However the settings are not honored at startup.

Tested with krakatau and cfr.

**Comment by samczsun** [comment]
The bootstrapper should automagically update you to the latest version :)

**Comment by Janmm14** [comment]
I just need to download the new bootstrapper first, I think.

**Comment by samczsun** [comment]
Wait a sec. Forgot to fix something in bootstrapper :(

**Comment by samczsun** [comment]
Done

**Comment by Janmm14** [comment]
@samczsun You mean the ```Could not rename``` error?

**Comment by samczsun** [comment]
Yep. That's fixed now

**Comment by Janmm14** [comment]
Thanks, it works now.
